-- ========================================
-- CRÉATION DES TABLES SUPABASE POUR GESTION NOTES
-- ========================================

-- 1. Table des élèves (students)
-- ========================================
CREATE TABLE IF NOT EXISTS students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index pour optimiser les performances
CREATE INDEX IF NOT EXISTS idx_students_user_id ON students(user_id);
CREATE INDEX IF NOT EXISTS idx_students_created_at ON students(created_at);

-- Trigger pour mettre à jour updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_students_updated_at 
    BEFORE UPDATE ON students 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- 2. Table des notes (grades)
-- ========================================
CREATE TABLE IF NOT EXISTS grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    subject_id VARCHAR(100) NOT NULL, -- ex: 'boker_sadot', 'iyun', 'graphisme', etc.
    notes JSONB DEFAULT '[]', -- Array de 4 notes: [null, null, null, null]
    week INTEGER DEFAULT 1, -- Numéro de la semaine (1-4)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index pour optimiser les performances
CREATE INDEX IF NOT EXISTS idx_grades_user_id ON grades(user_id);
CREATE INDEX IF NOT EXISTS idx_grades_student_id ON grades(student_id);
CREATE INDEX IF NOT EXISTS idx_grades_subject_id ON grades(subject_id);
CREATE INDEX IF NOT EXISTS idx_grades_week ON grades(week);
CREATE INDEX IF NOT EXISTS idx_grades_user_student ON grades(user_id, student_id);

-- Contrainte unique pour éviter les doublons
ALTER TABLE grades ADD CONSTRAINT grades_user_student_subject_unique 
    UNIQUE (user_id, student_id, subject_id);

-- Trigger pour mettre à jour updated_at
CREATE TRIGGER update_grades_updated_at 
    BEFORE UPDATE ON grades 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- ========================================
-- ROW LEVEL SECURITY (RLS)
-- ========================================

-- Activer RLS sur les deux tables
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE grades ENABLE ROW LEVEL SECURITY;

-- 3. Politiques de sécurité pour la table students
-- ========================================

-- Politique de lecture : les utilisateurs ne peuvent voir que leurs propres élèves
CREATE POLICY "Users can view their own students" ON students
    FOR SELECT USING (auth.uid() = user_id);

-- Politique d'insertion : les utilisateurs ne peuvent insérer que pour eux-mêmes
CREATE POLICY "Users can insert their own students" ON students
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Politique de mise à jour : les utilisateurs ne peuvent modifier que leurs propres élèves
CREATE POLICY "Users can update their own students" ON students
    FOR UPDATE USING (auth.uid() = user_id);

-- Politique de suppression : les utilisateurs ne peuvent supprimer que leurs propres élèves
CREATE POLICY "Users can delete their own students" ON students
    FOR DELETE USING (auth.uid() = user_id);

-- 4. Politiques de sécurité pour la table grades
-- ========================================

-- Politique de lecture : les utilisateurs ne peuvent voir que leurs propres notes
CREATE POLICY "Users can view their own grades" ON grades
    FOR SELECT USING (auth.uid() = user_id);

-- Politique d'insertion : les utilisateurs ne peuvent insérer que pour eux-mêmes
CREATE POLICY "Users can insert their own grades" ON grades
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Politique de mise à jour : les utilisateurs ne peuvent modifier que leurs propres notes
CREATE POLICY "Users can update their own grades" ON grades
    FOR UPDATE USING (auth.uid() = user_id);

-- Politique de suppression : les utilisateurs ne peuvent supprimer que leurs propres notes
CREATE POLICY "Users can delete their own grades" ON grades
    FOR DELETE USING (auth.uid() = user_id);

-- ========================================
-- FONCTIONS UTILITAIRES
-- ========================================

-- Fonction pour récupérer tous les élèves d'un utilisateur avec leurs notes
CREATE OR REPLACE FUNCTION get_user_students_with_grades(p_user_id UUID)
RETURNS TABLE (
    student_id BIGINT,
    first_name VARCHAR,
    last_name VARCHAR,
    student_created_at TIMESTAMP WITH TIME ZONE,
    student_updated_at TIMESTAMP WITH TIME ZONE,
    grade_id BIGINT,
    subject_id VARCHAR,
    notes JSONB,
    week INTEGER,
    grade_created_at TIMESTAMP WITH TIME ZONE,
    grade_updated_at TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        s.id as student_id,
        s.first_name,
        s.last_name,
        s.created_at as student_created_at,
        s.updated_at as student_updated_at,
        g.id as grade_id,
        g.subject_id,
        g.notes,
        g.week,
        g.created_at as grade_created_at,
        g.updated_at as grade_updated_at
    FROM students s
    LEFT JOIN grades g ON s.id = g.student_id
    WHERE s.user_id = p_user_id
    ORDER BY s.created_at, g.subject_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant sur la fonction
GRANT EXECUTE ON FUNCTION get_user_students_with_grades TO authenticated;

-- ========================================
-- PERMISSIONS
-- ========================================

-- Donner les permissions nécessaires aux utilisateurs authentifiés
GRANT ALL ON students TO authenticated;
GRANT ALL ON grades TO authenticated;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- ========================================
-- VALIDATION DES DONNÉES
-- ========================================

-- Contrainte de validation pour le numéro de semaine
ALTER TABLE grades ADD CONSTRAINT grades_week_check 
    CHECK (week >= 1 AND week <= 4);

-- Contrainte de validation pour les noms (non vides)
ALTER TABLE students ADD CONSTRAINT students_first_name_check 
    CHECK (length(trim(first_name)) > 0);

ALTER TABLE students ADD CONSTRAINT students_last_name_check 
    CHECK (length(trim(last_name)) > 0);

-- ========================================
-- NETTOYAGE (optionnel - décommenter si nécessaire)
-- ========================================

-- Pour recréer les tables complètement (décommentez si nécessaire)
/*
DROP TABLE IF EXISTS grades CASCADE;
DROP TABLE IF EXISTS students CASCADE;
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;
DROP FUNCTION IF EXISTS get_user_students_with_grades(UUID) CASCADE;
*/

-- ========================================
-- FIN DU SCRIPT
-- ========================================
